version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t $DOCKER_USER/test:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push  $DOCKER_USER/test:$CIRCLE_BRANCH
     
     - run: ssh-add - <<< "$AZURE_SSH" && echo "$AZURE_USER $AZURE_IP" 
